N-gramas (n-gramas)

In [33]:
frase = "ele sabia que eu sabia trabahar com IA e sabia que eu estava estudando tecnologia sabia disso"

In [34]:
# O split transforma a frase ou qualquer texto em lista

palavras = frase.split()
palavras

['ele',
 'sabia',
 'que',
 'eu',
 'sabia',
 'trabahar',
 'com',
 'IA',
 'e',
 'sabia',
 'que',
 'eu',
 'estava',
 'estudando',
 'tecnologia',
 'sabia',
 'disso']

In [35]:
import pandas as pd
tabela = pd.DataFrame({"palavras":palavras})
tabela

      palavras
0          ele
1        sabia
2          que
3           eu
4        sabia
5     trabahar
6          com
7           IA
8            e
9        sabia
10         que
11          eu
12      estava
13   estudando
14  tecnologia
15       sabia
16       disso

In [36]:
tabela["proxima_palavra"] = tabela["palavras"].shift(-1)
tabela

      palavras proxima_palavra
0          ele           sabia
1        sabia             que
2          que              eu
3           eu           sabia
4        sabia        trabahar
5     trabahar             com
6          com              IA
7           IA               e
8            e           sabia
9        sabia             que
10         que              eu
11          eu          estava
12      estava       estudando
13   estudando      tecnologia
14  tecnologia           sabia
15       sabia           disso
16       disso             NaN

In [37]:
tabela = tabela.dropna()
tabela

      palavras proxima_palavra
0          ele           sabia
1        sabia             que
2          que              eu
3           eu           sabia
4        sabia        trabahar
5     trabahar             com
6          com              IA
7           IA               e
8            e           sabia
9        sabia             que
10         que              eu
11          eu          estava
12      estava       estudando
13   estudando      tecnologia
14  tecnologia           sabia
15       sabia           disso

In [38]:
filtro = tabela["palavras"] == "eu"
tabela[filtro]

   palavras proxima_palavra
3        eu           sabia
11       eu          estava

In [39]:
tabela[filtro]["palavras"].value_counts()

palavras
eu    2
Name: count, dtype: int64

In [40]:
tabela[filtro]["proxima_palavra"].value_counts(normalize=True)

proxima_palavra
sabia     0.5
estava    0.5
Name: proportion, dtype: float64

In [41]:
tabela[filtro]["proxima_palavra"].value_counts().idxmax()

'sabia'